In [3]:
import numpy as np


In [5]:
my_list =[1,2,3,4]

In [7]:
np.array(my_list)

array([1, 2, 3, 4])

In [9]:
my_2d_list =[[1,2,3,4],[10,20,30,40],[100,200,300,400]]

In [11]:
np.array(my_2d_list)

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])

In [17]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [19]:
np.ones(2)

array([1., 1.])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [33]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [35]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
#identical array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.random.rand(5)

array([0.72200576, 0.18242557, 0.41613652, 0.72212627, 0.1992136 ])

In [45]:
np.random.rand(3,4)

array([[0.53900495, 0.77781405, 0.56990767, 0.89528916],
       [0.4818591 , 0.02439477, 0.45482656, 0.12046809],
       [0.61397566, 0.8188553 , 0.01275568, 0.4032336 ]])

In [47]:
np.random.randn(2)

array([ 2.56802146, -0.61030439])

In [49]:
np.random.randn(2,4)

array([[-0.19372734, -0.11820195,  0.80246685,  1.21920852],
       [-0.31483143,  0.84048667,  0.25755343, -0.13079402]])

In [59]:
np.random.randint(3,120)

11

In [61]:
np.random.randint(3,120,3)

array([ 15, 106,  99])

In [73]:
arr = np.arange(4,16,2)

In [75]:
arr

array([ 4,  6,  8, 10, 12, 14])

In [79]:
arr[2:]

array([ 8, 10, 12, 14])

In [81]:
arr[:3]

array([4, 6, 8])

In [85]:
arr[2:4]

array([ 8, 10])

In [97]:
arr = np.array([[1,2,3,4],[4,5,6,8],[7,8,9,2],[11,12,13,23]])

In [99]:
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  8],
       [ 7,  8,  9,  2],
       [11, 12, 13, 23]])

In [111]:
arr[1:3,2:4]

array([[6, 8],
       [9, 2]])

In [155]:
arr = np.arange(50)

In [157]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [161]:
new_arr = arr.reshape(5,10)

In [163]:
new_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [165]:
new_arr[2:,5:8]

array([[25, 26, 27],
       [35, 36, 37],
       [45, 46, 47]])

In [202]:
from numpy.random import randn
np.random.seed(101)

In [204]:
randn(5,5)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575,  0.65111795],
       [-0.31931804, -0.84807698,  0.60596535, -2.01816824,  0.74012206],
       [ 0.52881349, -0.58900053,  0.18869531, -0.75887206, -0.93323722],
       [ 0.95505651,  0.19079432,  1.97875732,  2.60596728,  0.68350889],
       [ 0.30266545,  1.69372293, -1.70608593, -1.15911942, -0.13484072]])